# Generated by Django 3.0.2 on 2020-02-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNews', '0005_category_news_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='details',
            field=models.CharField(max_length=50000, null=True),
        ),
    ]
