# Generated by Django 3.0.2 on 2020-03-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNews', '0006_auto_20200210_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('newsid', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('userimage', models.ImageField(upload_to='comment_image')),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
    ]
