# Generated by Django 3.0.2 on 2020-03-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNews', '0008_auto_20200304_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
